---

- name: "password cannot be blank"
  fail:
    msg: "password cannot be blank"
  when: rslsync_webui_password|default('') == ''

- name: "add apt key"
  apt_key:
    url: "http://linux-packages.resilio.com/resilio-sync/key.asc"

- name: "add apt repository"
  apt_repository:
    repo: "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free"

- name: "install package"
  apt:
    pkg: "resilio-sync"
    state: "present"

- name: "generate config file"
  template:
    src: "config.json.j2"
    dest: "{{rslsync_config_path}}"
    mode: "0644"
    owner: "root"
    group: "root"
  no_log: true
  notify:
    - "restart rslsync"

- name: "add users to rslsync group"
  user:
    name: "{{item}}"
    groups: "rslsync"
    append: "yes"
  with_items: "{{rslsync_users}}"
